[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "AI-Assistant"
version = "0.1.0"
description = "This is a local AI Assistant called Intel that can come in handy for different desktop tasks."
readme = "README.md"
requires-python = ">=3.8"
authors = [
    {name = "Maksym Shevtsov", email = "max.shvtsv@gmail.com"},
]

dependencies = [
    "setuptools>=75,<82",
    "numpy>=1.26",
    "ollama>=0.6",
    "faster-whisper==1.2.1",
    "scipy>=1.11",
    "sounddevice==0.5.5",
    "openwakeword==0.6.0",
    "python-dotenv>=1.0",
    "requests>=2.31",
    "pystray>=0.19",
    "Pillow>=10.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
]
build = [
    "pyinstaller>=6.6",
]
